help: "t.me/afekvova"
key: ""

# Настройка расположения файлов
directory-settings:
  # Папка, в которой будет находится Excel файл
  parent: "/"
  # Название файла Excel. <название>.xls
  output-name: "output.xls"
  # Название листа Excel
  sheet-name: "products"

# Как будет работать макрос
macros-settings:
  # Как работает макрос
  # 0 - Поиск информации о новых товарах и добавление их в таблицу
  # 1 - Обновление информации о товарах
  # 2 - Обновление информации о товарах и поиск информации о новых товарах, добавление их в таблицу
  mode: 2
  # В течении какого времени можно заходить на сервер после получения мотд сервера
  cache-time: 12
